package app.rawline.core.render

import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.pow
import kotlin.math.roundToInt

/**
 * Small ICC profiles (version 2.4, matrix and curve) for the two output spaces the exporter offers, so a TIFF carries its
 * colour space instead of being read as sRGB by every viewer. Both spaces use the sRGB transfer curve; the colorants are the
 * primaries adapted from D65 to the ICC D50 connection space with the Bradford matrix (the same way the engine's own
 * ProPhoto to sRGB and ProPhoto to P3 matrices are built).
 */
object IccProfiles {
    fun srgb(): ByteArray = srgbBytes
    fun displayP3(): ByteArray = p3Bytes

    private val srgbBytes by lazy { build("sRGB IEC61966-2.1 (Rawline)", doubleArrayOf(0.640, 0.330, 0.300, 0.600, 0.150, 0.060)) }
    private val p3Bytes by lazy { build("Display P3 (Rawline)", doubleArrayOf(0.680, 0.320, 0.265, 0.690, 0.150, 0.060)) }

    private val d65 = doubleArrayOf(0.3127, 0.3290)
    internal val d50 = doubleArrayOf(0.9642, 1.0, 0.8249)   // the ICC profile connection space white

    private fun xyzOf(x: Double, y: Double) = doubleArrayOf(x / y, 1.0, (1.0 - x - y) / y)

    private fun inv3(m: DoubleArray): DoubleArray {
        val a = m[0]; val b = m[1]; val c = m[2]; val d = m[3]; val e = m[4]; val f = m[5]; val g = m[6]; val h = m[7]; val i = m[8]
        val det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
        return doubleArrayOf(
            (e * i - f * h) / det, (c * h - b * i) / det, (b * f - c * e) / det,
            (f * g - d * i) / det, (a * i - c * g) / det, (c * d - a * f) / det,
            (d * h - e * g) / det, (b * g - a * h) / det, (a * e - b * d) / det)
    }

    private fun mul3(a: DoubleArray, b: DoubleArray) = DoubleArray(9) { k -> val r = k / 3; val c = k % 3; a[r * 3] * b[c] + a[r * 3 + 1] * b[3 + c] + a[r * 3 + 2] * b[6 + c] }
    private fun mulV(m: DoubleArray, v: DoubleArray) = DoubleArray(3) { r -> m[r * 3] * v[0] + m[r * 3 + 1] * v[1] + m[r * 3 + 2] * v[2] }

    /** Colorants (columns: red, green, blue) in XYZ D50 for primaries given as xy pairs with a D65 white. Row major 3x3. */
    internal fun colorantsD50(xy: DoubleArray): DoubleArray {
        val r = xyzOf(xy[0], xy[1]); val g = xyzOf(xy[2], xy[3]); val b = xyzOf(xy[4], xy[5])
        val prim = doubleArrayOf(r[0], g[0], b[0], r[1], g[1], b[1], r[2], g[2], b[2])
        val white65 = xyzOf(d65[0], d65[1])
        val s = mulV(inv3(prim), white65)
        val rgbToXyz65 = DoubleArray(9) { k -> prim[k] * s[k % 3] }
        // Bradford chromatic adaptation D65 -> D50
        val bf = doubleArrayOf(0.8951, 0.2664, -0.1614, -0.7502, 1.7135, 0.0367, 0.0389, -0.0685, 1.0296)
        val src = mulV(bf, white65); val dst = mulV(bf, d50)
        val scale = doubleArrayOf(dst[0] / src[0], 0.0, 0.0, 0.0, dst[1] / src[1], 0.0, 0.0, 0.0, dst[2] / src[2])
        val adapt = mul3(inv3(bf), mul3(scale, bf))
        return mul3(adapt, rgbToXyz65)
    }

    /** sRGB encoded value (0..1) to linear light (0..1). */
    internal fun srgbToLinear(v: Double) = if (v <= 0.04045) v / 12.92 else ((v + 0.055) / 1.055).pow(2.4)

    private fun s15(v: Double) = (v * 65536.0).roundToInt()

    private fun build(description: String, primariesXy: DoubleArray): ByteArray {
        val col = colorantsD50(primariesXy)
        val tags = ArrayList<Pair<String, ByteArray>>()
        tags += "desc" to descTag(description)
        tags += "cprt" to textTag("Public domain. Generated by Rawline.")
        tags += "wtpt" to xyzTag(d50)
        tags += "rXYZ" to xyzTag(doubleArrayOf(col[0], col[3], col[6]))
        tags += "gXYZ" to xyzTag(doubleArrayOf(col[1], col[4], col[7]))
        tags += "bXYZ" to xyzTag(doubleArrayOf(col[2], col[5], col[8]))
        val trc = curveTag()
        val tableSize = 4 + 12 * (tags.size + 3)   // count, the listed tags and the three curves that share one table
        var offset = 128 + tableSize
        val offsets = ArrayList<Int>()
        tags.forEach { offsets += offset; offset += pad4(it.second.size) }
        val trcOffset = offset
        offset += pad4(trc.size)
        val total = offset

        val b = ByteBuffer.allocate(total).order(ByteOrder.BIG_ENDIAN)
        b.putInt(total)
        b.putInt(0)                        // preferred CMM: none
        b.putInt(0x02400000)               // version 2.4
        b.put("mntr".toByteArray(Charsets.US_ASCII))
        b.put("RGB ".toByteArray(Charsets.US_ASCII))
        b.put("XYZ ".toByteArray(Charsets.US_ASCII))
        b.putShort(2024).putShort(1).putShort(1).putShort(0).putShort(0).putShort(0)   // creation date (fixed, so the bytes are reproducible)
        b.put("acsp".toByteArray(Charsets.US_ASCII))
        b.putInt(0); b.putInt(0); b.putInt(0); b.putInt(0)   // platform, flags, manufacturer, model
        b.putLong(0)                       // attributes
        b.putInt(0)                        // rendering intent: perceptual
        b.putInt(s15(d50[0])); b.putInt(s15(d50[1])); b.putInt(s15(d50[2]))   // illuminant
        b.putInt(0)                        // creator
        b.position(128)                    // profile ID and reserved bytes stay zero
        b.putInt(tags.size + 3)
        tags.forEachIndexed { i, (sig, data) -> b.put(sig.toByteArray(Charsets.US_ASCII)).putInt(offsets[i]).putInt(data.size) }
        for (sig in listOf("rTRC", "gTRC", "bTRC")) b.put(sig.toByteArray(Charsets.US_ASCII)).putInt(trcOffset).putInt(trc.size)
        check(b.position() == 128 + tableSize)
        tags.forEachIndexed { i, (_, data) -> b.position(offsets[i]); b.put(data) }
        b.position(trcOffset); b.put(trc)
        return b.array()
    }

    private fun pad4(n: Int) = (n + 3) and 3.inv()

    private fun xyzTag(v: DoubleArray): ByteArray {
        val b = ByteBuffer.allocate(20).order(ByteOrder.BIG_ENDIAN)
        b.put("XYZ ".toByteArray(Charsets.US_ASCII)).putInt(0).putInt(s15(v[0])).putInt(s15(v[1])).putInt(s15(v[2]))
        return b.array()
    }

    private fun textTag(s: String): ByteArray {
        val ascii = s.toByteArray(Charsets.US_ASCII)
        val b = ByteBuffer.allocate(8 + ascii.size + 1).order(ByteOrder.BIG_ENDIAN)
        b.put("text".toByteArray(Charsets.US_ASCII)).putInt(0).put(ascii).put(0)
        return b.array()
    }

    // textDescriptionType (v2): ASCII, then empty Unicode and ScriptCode parts
    private fun descTag(s: String): ByteArray {
        val ascii = s.toByteArray(Charsets.US_ASCII)
        val b = ByteBuffer.allocate(12 + ascii.size + 1 + 4 + 4 + 2 + 1 + 67).order(ByteOrder.BIG_ENDIAN)
        b.put("desc".toByteArray(Charsets.US_ASCII)).putInt(0).putInt(ascii.size + 1).put(ascii).put(0)
        return b.array()   // the remaining bytes (Unicode count 0, ScriptCode count 0, 67 byte Macintosh field) are zero
    }

    private const val CURVE_POINTS = 1024

    /** 'curv' table: the sRGB transfer function as 1024 uint16 samples (encoded value in, linear value out). */
    internal fun curveTag(): ByteArray {
        val b = ByteBuffer.allocate(12 + CURVE_POINTS * 2).order(ByteOrder.BIG_ENDIAN)
        b.put("curv".toByteArray(Charsets.US_ASCII)).putInt(0).putInt(CURVE_POINTS)
        for (i in 0 until CURVE_POINTS) b.putShort((srgbToLinear(i / (CURVE_POINTS - 1.0)) * 65535.0).roundToInt().coerceIn(0, 65535).toShort())
        return b.array()
    }
}
