# Usage: cmake -DSHADER_DIR=... -DOUT=... -P gen_shaders.cmake
file(GLOB SHADERS ${SHADER_DIR}/*.glsl ${SHADER_DIR}/*.frag)
set(HDR "// Generated from shaders/ by gen_shaders.cmake. Do not edit.\n#pragma once\n#include <cstring>\n")
set(LOOKUP "")
foreach(S ${SHADERS})
    get_filename_component(N ${S} NAME)
    string(REPLACE "." "_" ID ${N})
    file(READ ${S} CONTENT)
    string(APPEND HDR "static const char *SH_${ID} = R\"GLSLSRC(${CONTENT})GLSLSRC\";\n")
    string(APPEND LOOKUP "    if (!std::strcmp(n, \"${N}\")) return SH_${ID};\n")
endforeach()
string(APPEND HDR "static inline const char *shaderByName(const char *n) {\n${LOOKUP}    return nullptr;\n}\n")
file(WRITE ${OUT}.tmp "${HDR}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT}.tmp ${OUT})
